default_stages: [push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: 'techs.json$'
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystem
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt
      - id: detect-private-key
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: make lint/ruff
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make lint/black
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: make lint/mypy
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: make lint/bandit
        language: system
        types: [python]
        pass_filenames: false
  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: make lint/safety
        language: system
        types: [python]
        pass_filenames: false
